FROM influx6/redis-golang-1.11.4-alpine-base:0.1

RUN apk update && apk add --no-cache gcc g++

RUN mkdir -p /go/src/github.com/gokit/npkg
WORKDIR /go/src/github.com/gokit/npkg
COPY . .

RUN export GO111MODULE=auto && \
      chmod -R +x ./scripts/ && \
      go get -v ./... 

ENTRYPOINT ["make ci"]